name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  # Checkout项目
      uses: actions/checkout@master
    - name: Set up Node.js  # Nodejs版本
      uses: actions/setup-node@master
      with:
        node-version: 12.13.0
    - name: Install and Build 
      run: |
          npm install
          npm run gallery-build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: dist/gallery 
